### ISSUE TITLE
Upgrade Libs

### ISSUE THREAD

**Issue by dobsc89** [playframework/play1#1046]
Upgrade core libs to latest stable versions:

- [ ] Netty 4.1.x
- [ ]  Hibernate 5.2.x

**Comment by asolntsev** [comment]
@dobsc89 It's not that simple. 
* I tried to upgrade Netty and got some compilation errors. It's doable, but somebody needs to review & update Play code to use newer Netty APIs.
* Newest Hibernate doesn't contain class `org.hibernate.ejb.Ejb3Configuration` anymore. Play uses this class. It's doable, but somebody should upgrade Hibernate initialization in `play.db.jpa.JPAPlugin`. See https://play.lighthouseapp.com/projects/57987/tickets/1818-hibernate-need-to-be-updated-to-v435

**Comment by asolntsev** [comment]
Upgrade of Hibernate done: https://github.com/playframework/play1/pull/1114

**Comment by dobsc89** [comment]
Thanks @asolntsev

**Comment by xael-fry** [comment]
We already have an issue for upgrade of netty [#1940](https://play.lighthouseapp.com/projects/57987/tickets/1940-upgrade-to-netty-4x)
