### ISSUE TITLE
Initialize play static field early

### ISSUE THREAD

**Issue by asolntsev** [playframework/play1#1064]
... to avoid `NullPointerException`s and make writing plain unit-tests easier.

Problem description: 
* Play has lot of `public static` field - first of all, `Play.configuration`
* Many classes do use these `public static` fields
* When writing unit-test or main method, developers always need to write null checks and boilerplate code for Play initialization, e.g.: 
`if (Play.configuration == null) Play.coniguration = new Properties();`

We want to improve it.
Let's initialize **early** as many Play fields as possible.

**Comment by xael-fry** [comment]
@asolntsev .
Thanks, merged and pushed in 1.4.x
