### ISSUE TITLE
Warning on missing dependencies on "play deps --sync"

### ISSUE THREAD

**Issue by cbxp** [playframework/play1#1073]
We found that recent commit a1bbc0a affects depenencies sync producing the following message:

~ *****************************************************************************
~ WARNING: These dependencies are missing, your application may not work properly (use --verbose for details),
~
~	play->play 1.4: java.text.ParseException: inconsistent module descriptor file found in '/home/xp/work/play-1.4.x/framework/dependencies.yml': bad revision: expected='1.4.x-1.4.1-197-ga1bbc0a' found='1.4.x-1.4.1-197-ga1bbc0a'; 

We work with branch 1.4.x and made sure that there was no such issue before this commit.

**Comment by xael-fry** [comment]
Yes, all problems found when running dependencies where not shown to user, this commit just show dependencies error.
I your case you made that `play 1.4` is required but deps only found your local revision `'1.4.x-1.4.1-197-ga1bbc0a` that is different from `1.4`. so I think it is good to warn user that the version is not correct.

**Comment by asolntsev** [comment]
Actually this warning is useless for us. We want to use play 1.4.bla-bla

I suggest the following: we could declare dependency as "play 1.4.+", and
DependencyManager could understand it (like ant, maven and gradle).

**Comment by xael-fry** [comment]
Yes you should be able to declare [dynamic revision](https://www.playframework.com/documentation/1.4.x/dependency#Dynamicrevisions), Let me know if it is ok for you?

**Comment by asolntsev** [comment]
@xael-fry 
Yes, declaring dependency as `play 1.4.+` helped.
Thank you!
Closing the issue.
