### ISSUE TITLE
Allow custom implementation of base Controller

### ISSUE THREAD

**Issue by ryanitus** [playframework/play1#1095]
I would like to provide my own implementation of the underlying controller, so I can process my own code when an action like "render()" is called.

The ControllersEnhancer is essential to a proper functioning Controller, but it's hard coded to only work for play.mvc.Controller:

        if (field.getDeclaringClass().getName().equals("play.mvc.Controller") || field.getDeclaringClass().getName().equals("play.mvc.WebSocketController")) {

If this could be made more generic, I could provide my own implementation, so rather than controllers extending play.mvc.Controller, I could extend MyController instead.  I've verified it works locally by changing .equals("play.mvc.Controller") to .startsWith("play.mvc.").

**Comment by asolntsev** [comment]
@ryanitus I agree with you. 
I suggest to create a "marker" interface like `PlayController`, so that

* `play.mvc.Controller` implements `PlayController`
* `YourCustomController` implements `PlayController`

Can you prepare a pull request, or do you need my help?

**Comment by asolntsev** [comment]
Hi @ryanitus !
I have prepared pull request for your suggestion: https://github.com/playframework/play1/pull/1102
Could you review it?
Does it solve your problem?
