### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by Roland4444** [playframework/play1#1111]
Hello! On your tutorial Play 1.4 https://playframework.com/documentation/1.4.x/asynchronous#HTTPresponsestreaming

Article about Websockets:

wtitten
""""""""On the browser side, you open a socket using a “ws://” url:
new Socket("ws://localhost:9000/helloSocket?name=Guillaume")"""""

MUST BE """"""""""
new WebSocket("ws://localhost:9000/helloSocket?name=Guillaume");
"""""""""""""""""""""

THX FOR ATTENTION!

**Comment by asolntsev** [comment]
@Roland4444 Thank you! I have prepared a fix: https://github.com/playframework/play1/pull/1116
