### ISSUE TITLE
https render to http

### ISSUE THREAD

**Issue by wenjiech** [playframework/play1#1124]
Hi, i use play in version 1.2.7 when i have a request by https protocol, but it render to http. is there sth wrong in my configuration? how can i solve this problem , tks!

**Comment by Alvaroisit** [comment]
Use a load balancer/proxy server such as Nginx to handle your secured traffic.


server {
	# SSL configuration
	listen 443 ssl default_server;
	listen [::]:443 ssl default_server;
	server_name _;
	ssl_certificate		/etc/letsencrypt/live/www.example.com/cert.pem;
	ssl_certificate_key	/etc/letsencrypt/live/www.example.com/privkey.pem;
	ssl_protocols		TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers		HIGH:!aNULL:!MD5;

	#listen 443
	location / {
		proxy_set_header	X-Real-IP 	$remote_addr;
		proxy_set_header 	X-Forwarded-For	$proxy_add_x_forwarded_for;
		proxy_set_header	Host		$host;

		proxy_pass http://127.0.0.1:9000;
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		#try_files $uri $uri/ =404;
	}
}

**Comment by asolntsev** [comment]
@wenjiech To be honest, I don't understand your question. 
Anyway, I guess we had some fixes for https support in play 1.4.x. Don't you want to upgrade to play 1.4.4?
