### ISSUE TITLE
Modules removed from playframework.com?

### ISSUE THREAD

**Issue by WillemMali** [playframework/play1#1145]
My build broke because I cleared my ivy2 cache. Is there any place where I can still find old play modules such as `less-0.3.compatibility` and `sass-1.1`?

**Comment by WillemMali** [comment]
And is there a way to get `play install sass-1.1` to work again?

**Comment by asolntsev** [comment]
I don't know. 
@xael-fry Can you help with it?

**Comment by WillemMali** [comment]
I was able to fix it by manually downloading the module zips and extracting
them to `$PLAY_HOME/modules/$MODULE`, but it used to work with just `play
dependencies --sync` (that command now emits a few TLS EC errors relating
to the modules if you run it with `--debug`).

**Comment by xael-fry** [comment]
It is fixed in 1.4.x and master branch. cf issue #1126 1126
