### ISSUE TITLE
JPA/HQL/jpql positional parameters 

### ISSUE THREAD

**Issue by djole103** [playframework/play1#1165]
Somewhere after 1.4.2 positional, unnumbered, arguments such as `ExampleModel.find("column1 = ? and column2 > ?")` became unsupported and results in intermittent errors, but given there were only patch releases I'd think this wasn't the desired behaviour.

**Comment by xael-fry** [comment]
@djole103 When we update hibernate positional param index was mark as warning but it should still work without it, but it is recommend to change it as it will be required in future release
