### ISSUE TITLE
500 error in Play tests returns 200 response

### ISSUE THREAD

**Issue by Fraserhardy** [playframework/play1#1175]
This is still present in 1.4.3 and is causing quite a few issues for us. I can see there was a PR for this but it seems to have since been forgotten: 

https://play.lighthouseapp.com/projects/57987/tickets/1849-exceptions-from-controllers-are-not-detected-in-functionaltests

If an exception is thrown by the controller then the response from the functional test should be 500 not 200 as is currently happening.

**Comment by sp00m** [comment]
Any updates concerning this issue?

**Comment by Fraserhardy** [comment]
Fixed in: https://github.com/playframework/play1/pull/1246
