### ISSUE TITLE
Update postgres driver

### ISSUE THREAD

**Issue by aleksandy** [playframework/play1#1216]
[Last versions](https://github.com/pgjdbc/pgjdbc/blob/48b98971d085a7988b67a31cf5ff9fb52c5534e5/pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSetMetaData.java#L355-L357) does not require [patching](https://github.com/playframework/play1/blob/master/framework/patches/pgjdbc.9.0.patch#L13).

**Comment by xabolcs** [comment]
And works with Postgres 9.6 and onwards. :+1:

**Comment by dejan2609** [comment]
Related PR: #1250

**Comment by asolntsev** [comment]
@aleksandy @dejan2609 PR https://github.com/playframework/play1/pull/1250 has been merged.
