### ISSUE TITLE
[play 1.5] documentation is missing

### ISSUE THREAD

**Issue by daohodac** [playframework/play1#1217]
The documentation is not available in https://playframework.com/documentation/2.6.x/Home
neither on http://localhost:9000/@documentation

**Comment by daohodac** [comment]
did I miss something or I am the only guy not to see it? is it possible to generate it from the sources?

**Comment by xael-fry** [comment]
@daohodac Documentation is online now https://www.playframework.com/documentation/1.5.x/home
but there is still some issue to dysplay the release documentation

**Comment by daohodac** [comment]
👍

**Comment by xael-fry** [comment]
Doc is now online
