### ISSUE TITLE
[#2154] NPE

### ISSUE THREAD

**Issue by flybyray** [playframework/play1#1219]
https://github.com/playframework/play1/blob/2338f92efabf63a3ad22c314a2151b686466f3f9/framework/src/play/jobs/JobsPlugin.java#L195

evaluates to `null`, if there is no application configuration.

The `@On` annotation does not allow a default value which could be provided for `getProperty`. Therefore the default should be `""`.

Reason:
https://github.com/playframework/play1/blob/2338f92efabf63a3ad22c314a2151b686466f3f9/framework/src/play/jobs/JobsPlugin.java#L197
will throw a NPE if `cron` is `null`.

**Comment by xael-fry** [comment]
Merged #1220 
Thanks
