### ISSUE TITLE
[#2155] Silent or suppressed errors in unittest PluginCollectionTest#skipsDuplicatePlugins

### ISSUE THREAD

**Issue by flybyray** [playframework/play1#1221]
02a75fb in PR #1138
Introduced resource "custom-play.plugins.duplicate" which depends on CorePlugin

15874d0 in PR #1144
Splitted CorePlugin into two Plugins with new Names and Location without modifying custom-play.plugins.duplicate.

Ant task unittest should fail because resource "custom-play.plugins.duplicate" file will not be copied ( see https://github.com/playframework/play1/blob/master/framework/build.xml#L397 ).
Hence the PR #1138 does not really test what it should test.

**Comment by xael-fry** [comment]
Merged and pushed in master
Thanks
