### ISSUE TITLE
1.5.2 on Release page

### ISSUE THREAD

**Issue by dcrall** [playframework/play1#1277]
@xael-fry Thank you for pushing out the release for play 1.5.2. I am wondering when it will appear on the release page: https://www.playframework.com/releases. This is the first time I've really watched the release process. I understand there may be a lag, but I wanted to make sure it didn't fall through the cracks. Thanks again for all your work.

**Comment by tomparle** [comment]
I do not know when it's going to be pushed there either, but I'd like to join you to thank everyone including @xael-fry for this new release !

**Comment by jvosloo** [comment]
You guys rock!!

**Comment by xael-fry** [comment]
@dcrall Release should appear soon on the website, In will let you know.
Thanks guys for working on it

**Comment by Fraserhardy** [comment]
Great work everyone. Nice to see the community still working on Play 1.

**Comment by renutz** [comment]
+1 Awesome!!!

**Comment by jamesbroadshaw** [comment]
Any progress on getting the release posted on the website? I use the old heroku buildpack which references the site and would like to give the new version a try.

**Comment by tomparle** [comment]
Hi @jamesbroadshaw ,
I understand your concern. In order not to have to wait for releases to be published, I customized the heroku buildpack to make it fetch my own Play build uploaded on S3.  If you look into the buildpack code, you will find some comments that points out how to do it, so I may suggest you to do the same so you will not depend anymore on the website releases.
I will send you more details if you cannot find on your own.

**Comment by tazmaniax** [comment]
I'm also using a custom buildpack which is very useful.

@tomparle  with the current Heroku Play buildpack https://github.com/heroku/heroku-buildpack-play I get the following warning on deployment...
```
remote: 
remote:  !   Warning: You are running on a deprecated stack.
remote:  !   Please upgrade to the latest stack by following the instructions on:
remote:  !   https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack
remote: 
```
Have you done anything about this?

**Comment by tomparle** [comment]
Hi @tazmaniax ,
this warning just tells you that you can/should upgrade your app to the latest Heroku stack, as explained here : https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack

Is your app running on the latest stack ? Currently it is Heroku-18 stack.
If it is already the case, maybe try to purge the buildcache repo as explained at the bottom of the same page.

**Comment by dcrall** [comment]
@xael-fry - ping. Is there any chance of this happening soon?

**Comment by dcrall** [comment]
Play 1.5.2 is now available on https://www.playframework.com/releases. This issue can be closed. Thank you!
