### ISSUE TITLE
Does not make sense to default MySQL character set and collation properties on connection URL

### ISSUE THREAD

**Issue by tazmaniax** [playframework/play1#1294]
### Play Version (1.5.x / etc)
1.5.2

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOS 10.14.4

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

### Library Dependencies
Connector/J v5.1.47

### Behaviour
Play currently [adds the following default parameters to the connection URL](https://github.com/playframework/play1/blob/cd4fca38a56ecc25561302911a79667b471cf827/framework/src/play/db/DBPlugin.java#L189):
* useUnicode=yes
* characterEncoding=UTF-8
* connectionCollation=utf8_general_ci

The [Connector/J 5.1 documentation on charsets](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-charsets.html) does not recommend these properties are set instead preferring...
> The character encoding between client and server is automatically detected upon connection (provided that the Connector/J connection properties characterEncoding and connectionCollation are not set).

As well if the server collation is not set to "utf8_general_ci" and that collation is not expected then unexpected results might occur.

In addition the [documentation](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html) for `useUnicode` states that...
> Should only be used when the driver can't determine the character set mapping, or you are trying to 'force' the driver to use a character set that MySQL either doesn't natively support.

I suggest these defaults are removed to allow the client to freely auto-detect the character set and collation from the server and avoid setting potentially unexpected and undesirable defaults.

**Comment by tazmaniax** [comment]
As a follow up, these current defaults actually stops utfmb4 from being used even with a properly configured MySQL v5.7 and the latest Connector/J version.

**Comment by sbeigel** [comment]
I can confirm that utf8mb4 works without these settings! Adding the following parameters to the connection URL can be a workaround (as they override the values in DBPlugin) until play's default config is changed/removed :

`useUnicode=&characterEncoding=&connectionCollation=`

**Comment by mohsen0** [comment]
> I can confirm that utf8mb4 works without these settings! Adding the following parameters to the connection URL can be a workaround (as they override the values in DBPlugin) until play's default config is changed/removed :
> 
> `useUnicode=&characterEncoding=&connectionCollation=`

it did not work for me.
```
Can't start in PROD mode with errors

Database error
A database error occurred : Cannot connected to the database[default], Unsupported character encoding ''
 / play.exceptions.DatabaseException / Cannot connected to the database[default], Unsupported character encoding ''
```
