### ISSUE TITLE
Define allowed methods used in 'X-HTTP-Method-Override'

### ISSUE THREAD

**Issue by xael-fry** [playframework/play1#1300]
### Play Version (1.5.x / etc)

Version 1.5

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 7 or linux

### JDK

Oracle 1.8

### Expected Behavior
 I want to be able to limit method that could be defined in 'X-HTTP-Method-Override'

### Actual Behavior

If 'X-HTTP-Method-Override' is defined all method will be handled by Play, we want to limit the impact of this header

**Comment by Fraserhardy** [comment]
We've found that although the header is disabled, its still possible to use X-HTTP-Method-Override by passing as a query string. This is handled by `play.mvc.Router#route(play.mvc.Http.Request)` separately from the Header.
