### ISSUE TITLE
Creating a worker in Play

### ISSUE THREAD

**Issue by cies** [playframework/play1#1303]
I've inherited a Play1 (P1) codebase and currently I'm trying to extend our infrastructure with a message queue server for work queues. There are three main options to reuse existing code (mainly the `app/models/**` code) that resides in the P1 codebase for "worker" that I'm trying to build.

1. Isolate the `app/models/**` code into a library, that can subsequently be used in both P1 and the worker (and possibly other projects as well). This seemed the hardest option since our MVC separation was not strictly adhered).
2. Create a new `main` entry point in P1 that does not startup the whole Play FW, but just enough so the`app/models/**` code can be used. This new `main` function kicks off the event loop that listens to the queue server.
3. Add a configuration option that switches the P1 app into a "worker" mode. The code still accepts HTTP traffic, we just do not send any of that traffic to it (as per LB config).

I got started with nr2 and in this effort tried to set up a gradle project for P1. I found issue #1201 and tried to get it going from there, but ran into:

```
Error during the 500 response generation
Oops: UnexpectedException
Unexpected error : While applying play.plugins.EnhancerPlugin[...]
```

I'm about to give up on 2 (and thereby implicitly on 1 as well) as I cannot work around this error. Any insights or tips on this point are very welcome. I found [this on SO](https://stackoverflow.com/questions/40502905) but that did not get me any further (they seem to be similar error with different causes).

Sorry to abuse this place if asking for help, but when it comes to Play 1.x related stuff I think this is the place where it's happening. The differences between 1.x and 2.x are big enough that knowledge on one is not likely to carry over to the other. If there is an other place: please let me know.

Anyone that knows how to precompile a 1.x project from gradle and wants to share: I'm most interested.

**Comment by megamattron** [comment]
I think 3 is probably the most straightforward option honestly. It would also be probably be fairly doable to port the models over to straight hibernate and remove the play1 dependency all together. You'll probably some good test cases to be sure though, as the lifecycle and saving are fairly different.

**Comment by cies** [comment]
Thanks. That's what we ended up doing. Closing this.
