### ISSUE TITLE
Upgrade java mail and commons email

### ISSUE THREAD

**Issue by sant0s** [playframework/play1#1309]
### Play Version

1.5.3

### Operating System

Ubuntu 18.04

### JDK

Oracle 1.8.0_201-b09

### Description

Sending email using the SimpleMail class, as explained in

https://www.playframework.com/documentation/1.5.x/emails

via an SSL-enabled SMTP server fails with

`javax.mail.AuthenticationFailedException: 535 Incorrect authentication data`

(at least) in a scenario where the password includes special characters.

Keeping the credentials untouched and adding

```
- com.sun.mail -> javax.mail 1.6.2:
       force: true
```

to the app's dependencies.yml and executing

`play dependencies`

fixes the issue.

Therefore, Play's own dependencies.yml's javax.mail version should be upgraded.

While at it, one can also upgrade apache commons email to 1.5.

`- org.apache.commons -> commons-email 1.5`

**Comment by xael-fry** [comment]
Merge and pushed in master
Thanks
