### ISSUE TITLE
JDK 13/14 support

### ISSUE THREAD

**Issue by tomparle** [playframework/play1#1324]
Hi everybody,

with the upcoming release of JDK 14 in March, I think we should try to be up-to-date with the latest JDK. I have spent several hours to start the work to support JDK 13, and here are the state so far :

- Groovy upgraded to 2.5.8 (for jdk13 compatibility)
- Jaxen upgraded to 1.2.0 (to avoid module conflict with org.w3c.dom)
- one test had to be modified to prevent the use of reflection which has been forbidden by JDK-8210522 CSR.

It seems to work for simple projects, but I have two issues :
- the JDT Compiler gives "Type already existing errors" when hot-recompiling classes in dev mode. I could force a policy so that all compile errors are ignored to go further, but that's far from ideal
- modules do not work : the classes are not properly recompiled and lead to errors (like "FasterGT" : there are some conflicts between package names and compiled template names)

If you want to get a look or contribute, you can see the work in progress here : https://github.com/tomparle/play1/tree/upgrade-jdk-13

I'll try to make some more progress later but module errors seem hard to solve.
All comments appreciated !

**Comment by tazmaniax** [comment]
@tomparle I’ve had JDK13 running in production for a couple of months now and been meaning to raise a pull request. We’ll have a look

**Comment by tomparle** [comment]
Hi @tazmaniax ,
thank you for your reply !
Do you mean that you have been using Play with JDK 13 ? I would be surprised because it does not seem to run out of the box.
With pleasure to work together on this one ! (see details in my initial post)

**Comment by tazmaniax** [comment]
@tomparle I had to upgrade a number of libraries but otherwise it was good to go. Here is a summary of the dependency updates...
    - org.ow2.asm -> asm 7.2
    - org.ow2.asm -> asm-commons 7.2
    - org.ow2.asm -> asm-util 7.2
    - org.ow2.asm -> asm-tree 7.2
    - org.ow2.asm -> asm-analysis 7.2
    - org.codehaus.groovy -> groovy 2.5.8
    - org.codehaus.groovy -> groovy-xml 2.5.8
    - org.eclipse.jdt -> org.eclipse.jdt.core 3.18.0
    - org.javassist -> javassist 3.26.0-GA

I think I had a Groovy template issue with org.eclipse.jdt.core 3.19.0 so kept it at 3.18.0

**Comment by tazmaniax** [comment]
Oh you found the org.w3c.dom module conflict, cool! I spent ages trying to find that but it didn't block deployment for me so left it

**Comment by tomparle** [comment]
Thank you @tazmaniax for sharing this !
Indeed, there is a compilation regression starting from org.eclipse.jdt.core 3.19.0. Reverting to 3.18.0 fixed the module issues ! You helped us a lot here.

Unfortunately that means that we are currently limited to compiling sources up to JDK 12 (`java.source` parameter in application.conf), but that is not so much an issue for now. Still, it'd be great to be able to make future versions of jdt core work when we have some time to look at it.

I updated my branch and I think it's ready for a pull request, so I submitted it for review : https://github.com/playframework/play1/pull/1325

**Comment by tomparle** [comment]
Hi,

some update on this : I have also made the needed evolutions for compatibility with JDK 14, see https://github.com/tomparle/play1/tree/upgrade-jdk-14
There were only some libs to upgrade (Groovy to 3.x, asm, javassist and jdt compiler) and the `GroovyTemplateCompiler` class to fix.

Unfortunately, the Groovy migration causes the module `faster-gt` (Faster Groovy Template) to fail. The same `GroovyTemplateCompiler` in the gt-engine should be applied the same fix, but I do not have access to the gt-engine repository.

@asolntsev it seems that you are also maintaing the `Replay` fork of the Play! framework which seems more up to date, should we all join the efforts to this new project ? It is, unfortunately, becoming harder and harder to maintain.

**Comment by tomparle** [comment]
Hi Andrei,

thank you for your quick answer !
RePlay seems nice because it's up to date with more recent technologies,
and finally I also think that smaller and magicless is better.
I'm not sure I'm ready to switch yet because of all the modifications I
would have to do.

Is your team the only users of RePlay or are there other companies that use
it ?

I'll try to keep contributing on Play 1.x a little more in the meanwhile !
Thomas

**Comment by jvosloo** [comment]
Hi @tomparle, @tazmaniax and co... we're still big Play1 users and sincerely appreciate the effort you guys are putting in into keeping up with the latest Java versions etc. 

Big up to you guys! 💪 👏

**Comment by blinder** [comment]
yes, just to second @jvosloo really appreciative of the work and effort here! it has not gone unnoticed!

**Comment by tazmaniax** [comment]
@tomparle I had a look at the `faster-gt` issue a couple of weeks ago and even had a brief chat with the Eclipse Compiler folk. The chat was not overly productive but the long and short is it looks like there was change in the compiler to be a bit more strict around file naming that doesn't work well with the `faster-gt` approach of including the package name in the file name. If we can get `faster-gt` to use more conventional final names then we might be able to resolve this and move forward

**Comment by tomparle** [comment]
Wow, thank you for your support messages @jvosloo and @blinder, it was not expected and it's really motivating ! 
I'll try to dig a bit further into `faster-gt`, especially the `gt-engine`, whose RePlay version seems to be up to date, to deliver a functional JDK 14-compatible PR !
@tazmaniax thanks for your feedback. I think I remember these errors which occurs when we specify a java version > 11 in the `application.conf` file.  I'll see what can be done, but I think I will first try to make Play run with the new JDK, then in a second step make it compiles with the source > 11.

**Comment by tomparle** [comment]
I could make Play work with the JDK 14, but unfortunately the Eclipse JDT compiler lib upgrade makes the faster-gt plugin conflicts with generated compiled ressource names, as expected, which is unfortunate for those who uses it (like me).
@tazmaniax , would you have an idea of where to look in faster-gt code to change the naming policy ?

**Comment by asolntsev** [comment]
Just don't upgrade to the latest Eclipse jdt. Use the previous version
(which we use in replay). It works with Java 14.

ср, 3 июн. 2020 г., 2:26 Thomas Parle <notifications@github.com>:

**Comment by tomparle** [comment]
Thanks @asolntsev for the tip, indeed it's much easier to do this.

Here we go !
- I updated the `gt-engine` to be compatible with Groovy 3 : see PR https://github.com/tazmaniax/gt-engine/pull/1
-I updated the module `play-faster-gt` accordingly with this new gt-engine jar, see PR https://github.com/codeborne/play-fastergt/pull/2
- I prepared the Play upgrade for JDK up to 14 compatibility in this PR : https://github.com/playframework/play1/pull/1332

In brief, faster-gt users will have to use the new faster-gt once the PR is reviewed and accepted.

Feedback welcome !

**Comment by tomparle** [comment]
It was necessary because Play must be updated to Groovy 3 in order to be
compatible with jdk14.
RePlay guys have also updated their gt-engine version similarly.
But since I could have missed something, don't hesitate to test yourself
without modifying the gt engine version !

**Comment by tazmaniax** [comment]
Yes I have jdk14 running without the Groovy 3 upgrade. I wonder what I did differently

**Comment by tomparle** [comment]
That, I do not understand !
When I tried the first time with the original faster-gt module, the gt-engine jar threw an exception in the `GTGroovyCompileToClass` class, due to the same cast issue I had to fix in Play.
It seems that @asolntsev had to make the same fix in their version of gt-engine, so it seems mandatory.
