### ISSUE TITLE
Upgrade to Groovy 3

### ISSUE THREAD

**Issue by cies** [playframework/play1#1330]
After upgrading to JDK11 (from 8) we are now seeing the following error:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/usr/local/lib/play-1.5.3/framework/lib/groovy-2.5.3.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

A bit of searching led me to believe this is fixed in Groovy 3, which was recently released. Is an upgrade to Groovy 3 possible for Play1?

**Comment by tomparle** [comment]
Hi,
as stated in the log, this is not an error but a warning.
Your application should run without any issues. Did you try it ?

Moreover, release 3 of Groovy is a major one and the upgrade may be not so smooth.
If you would like to migrate soon and willy to help, what about reading the release notes and share with us what changes you think would be breaking ?
Thanks

**Comment by cies** [comment]
It all "just works", I just wondered if can be fixed with a simple dependency upgrade, or that it requires more work. Concluding this will be a lot more work, so I close this and just filter out the error somewhere :)

Thanks for the response.
