### ISSUE TITLE
cant remote debug with Java9 +

### ISSUE THREAD

**Issue by TemaniH** [playframework/play1#1331]
Can't remote debug when working with Java 9+.
https://github.com/playframework/play1/blob/e7b25e04218297a0393dafcd781f0f1123963bc1/framework/pym/play/application.py#L308

address arg has no ip address/hostname.

suggested solutions:
* expose new jdpa_host config param and if set use new syntax.
* resolve what java version is running and set accordingly.
* combine the 2 options and allow jdpa_host config param to have default value.

referencies:
* https://www.oracle.com/technetwork/java/javase/9-notes-3745703.html#JDK-8041435
* https://dev-aux.com/java/java-local-and-remote-jvm-debugging-jdk-8-and-later

**Comment by holajsh** [comment]
As this is very annoying problem when running Play app in a Docker container I have done a PR for this.
