### ISSUE TITLE
Release 1.6.0 issue with fastergt

### ISSUE THREAD

**Issue by tomparle** [playframework/play1#1349]
### Play Version
1.6.0

### JDK
13

### Library Dependencies
Faster GT 1.11

### Expected Behavior
Faster GT module should work without any issue

### Actual Behavior
Error when compiling the templates : 

`Caused by: play.template2.exceptions.GTCompilationException: Compile error. classname: play.template2.generated_templates.GTTemplate__play__framework_templates_errors_500_txt. message: The type GTTemplate__play__framework_templates_errors_500_txt collides with a package ln: 5
	at play.template2.compile.GTJavaCompileToClass$MyICompilerRequestor.acceptResult(GTJavaCompileToClass.java:122)
	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:588)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:475)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at play.template2.compile.GTJavaCompileToClass.compile(GTJavaCompileToClass.java:271)
	at play.template2.compile.GTCompiler.compile(GTCompiler.java:79)
	at play.template2.GTTemplateRepo.compileTemplate(GTTemplateRepo.java:290)
	... 10 more
`

@tazmaniax tell me if you encounter the same issue when testing this new release of Play ! This error reminds me of similar issues that I think you had fixed, maybe something's missing in the release ?

**Comment by tomparle** [comment]
Another regression detected : all templates are compiled in the root folder instead of the `tmp` folder, which is quite strange.

**Comment by tazmaniax** [comment]
@tomparle yes looks like the issue that we had before so looks like the latest FasterGT version is not being picked up. I did a quick compare of 1.6 to my current version and there are no code differences that would contribute to this. Looking at my repo of [faster-gt](https://github.com/tazmaniax/play-fastergt/releases) I think you need at least 1.11 and there is even a 1.12 with the updated Groovy support, although maybe your 1.10 build is ok.

**Comment by tomparle** [comment]
Thank you for your answer, after checking it up I indeed used FasterGT 1.11 (I edited my original post).
I will try with 1.12 to see if there is any difference, but the compiled templates at the root dir is still a mystery to me.

**Comment by tomparle** [comment]
@tazmaniax I tested again with FasterGT 1.12, indeed I was still using a custom build, because at the time I did not update with the version you updated on October 2020 for some reason.

I confirm that 1.6.0 works properly with FasterGT 1.12, thank you for pointing this out !
