### ISSUE TITLE
Switch to GitHub Actions, Travis will be removed

### ISSUE THREAD

**Issue by mkurz** [playframework/play1#1371]
Hey,

just to let you know, the Play 2 team is migrating all its repositories within the Play Framework organization to GitHub actions in the next weeks.
After that we intend to completely remove the Travis integration from the organization. Therefore I urge you to also move to GitHub actions in the play1 repository as well.
/cc @asolntsev @xael-fry

**Comment by tomparle** [comment]
Thank you @mkurz ,

with your current migration, would you have any guidelines / tips to help us migrating to GitHub actions ? (I'm not familiar with these)

**Comment by mkurz** [comment]
@tomparle
Play1 uses Travis to run tests:
https://github.com/playframework/play1/blob/0ecac3bc2421ae2dbec27a368bf671eda1c9cba5/.travis.yml#L14

For GH actions you need to define a workflow, e.g. have a look at https://github.com/playframework/play-json/blob/main/.github/workflows/build-test.yml.
Fortunately the workflow for play1 should be much simpler, there is even official documentation how to run tests with ant: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant
Problably you just need to replace the above `ant` command in that workflow (and probably also `on: pull_request`)

**Comment by xael-fry** [comment]
move to GitHub actions done.
;)

**Comment by mkurz** [comment]
Great!

**Comment by mkurz** [comment]
You still using the travis badge however:
![image](https://user-images.githubusercontent.com/644927/151779902-c98be34d-d607-4f4f-af5f-da3f58a4ca1c.png)

**Comment by xael-fry** [comment]
> You still using the travis badge however: ![image](https://user-images.githubusercontent.com/644927/151779902-c98be34d-d607-4f4f-af5f-da3f58a4ca1c.png)

Fix it, thanks
