### ISSUE TITLE
No issue, just a thank you

### ISSUE THREAD

**Issue by jvosloo** [playframework/play1#1388]
To all the committers of Play1 - I just wanted to give a big thank you for keeping at it, for keeping Play1 updated with the latest dependencies, the latest versions of Java, etc.

There's an admittedly small, but very thankful group of people in the world that still think Play1 is the best thing that ever happened to the Java web dev world.. and we're still waiting for something better to come along.

In the mean time, you guys are ensuring that the projects and products we're still running in production, are looked after and don't get stuck on old versions of stuff 👊 🙏

**Comment by ketain** [comment]
Seconded.
