### ISSUE TITLE
[1.7.0] Versions in the source are outdated: `ant version` produces `1.5.x-1.6.0-90-gf31919cd`

### ISSUE THREAD

**Issue by xabolcs** [playframework/play1#1398]
### Play Version (1.5.x / etc)
[1.7.0](https://github.com/playframework/play1/releases/tag/1.7.0) - currently at commit f31919cd68a6a5aec4fe397af4a8a932a9283a8b

### Expected Behavior

`ant version` produces 1.7 related version name, e.g.: `1.7.x-1.7.0`

### Actual Behavior

`ant version` produces version with old versionstrings: `1.5.x-1.6.0-90-gf31919cd`

### Reproducible Test Case

1. `git checkout 1.7.0`
2. `ant version`

```
$ git checkout 1.7.0
Note: switching to '1.7.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at f31919cd Merge pull request #1396 from xael-fry/1.7.0_documentation
$ ant version
Buildfile: /play1/framework/build.xml

version:
     [echo] Version 1.5.x-1.6.0-90-gf31919cd

BUILD SUCCESSFUL
Total time: 0 seconds
```

#### 1.5.x
`1.5.x` comes from [`build.xml`'s `baseversion`](https://github.com/playframework/play1/blob/1.7.0/framework/build.xml#L5).

`baseversion` shoud be updated!

#### 1.6.0-90

The `1.6.0-90-gf31919cd` comes from [`git describe --always`](https://git-scm.com/docs/git-describe):

       The command finds the most recent tag that is reachable from a commit. If the tag points to the commit, then only the tag is shown. Otherwise, it suffixes the tag name with the number of additional
       commits on top of the tagged object and the abbreviated object name of the most recent commit. The result is a "human-readable" object name which can also be used to identify the commit to other git
       commands.

       By default (without --all or --tags) git describe only shows annotated tags. For more information about creating annotated tags see the -a and -s options to git-tag(1).

`git` outputs `1.6.0-90` because it doesn't find tag `1.7.0`:
* tag `1.6.0` is annotated (created by `git tag --annotate ...`)
* tag `1.7.0` is a lightweight (not-annotated) tag

Tag "1.7.0" should be an annotated tag! See [git-tag(1)](https://git-scm.com/docs/git-tag)!

**Comment by xael-fry** [comment]
Fix it
