### ISSUE TITLE
Bytecode cache not being created on start

### ISSUE THREAD

**Issue by bigclumsyoaf** [playframework/play1#1422]
I'm trying to upgrade an old app from Play 1.0.3.4 to Play 1.7.1 running on Java 17.0.3.1.

I've made all the fixes to api changes etc, and everything works as expected in local `run` mode.

However when I try to `start` the app, none of the bytecode is cached. So every restart takes about 10 minutes, and then templates are compiled with each request. 

I tried to debug what is happening, the app is in PROD mode etc, but none of the bytecode is cached. 

I've started to add extra debug to my local install, and have found what looks like the problem to me. However this is in the framework code that hasn't changed for over 10 years, so either I'm completely misunderstanding what is going on, otherwise I can't understand how nobody else has had this issue? 😕 

In `BytecodeCache.cacheBytecode()` the first line is:

  `if (!Play.initialized || Play.tmpDir == null || Play.readOnlyTmp || !Play.configuration.getProperty("play.bytecodeCache","true").equals("true")) { return; }`

So bytecode caching is completely ignored if Play is not set to `initialized`. 

However in `Play.init()` the value of `Play.initialized` is only set to true, after `start()` is called, which is where all the compilation happens. If I set the value of initialized to true before `start()` is called, everything works as I would expect. Once everything is compiled, it starts up and runs much more quickly using the bytecode cache.

Can anyone help, or check that this is a problem?

**Comment by asolntsev** [comment]
@bigclumsyoaf When you start Play application in production mode, it's assumed the application should be precompiled by this moment. Did you run `play precompile` before `play start`?

**Comment by bigclumsyoaf** [comment]
@asolntsev No, is that mandatory now? It’s not something we ever did on play1.0, 1.2 or 1.3 apps we have in production. 

The code seems to handle `precompile` and compile under `start` differently, so assumed that both were acceptable. 

I did try running `precompile` while trying to get it to work, but received a different problem. I will need to check the specific error, but from memory it was a problem with commons io FileUtils, but that might have been a conflict with something under the app.

**Comment by asolntsev** [comment]
@bigclumsyoaf I don't remember if it's officially mandatory, but at least it seems reasonable to me. 

Starting in "Production mode" means that everything should be ready for start: the code is compiled etc. 

We even did a special move to eliminate from production build eclipse compiler and other dependencies needed only for compilation. It eliminates the risk that hacker manages to generate HTML file with a hacky groovy code in temporary folder and forces Play to compile it (in fact, we had such a vulnerability in production).

**Comment by bigclumsyoaf** [comment]
@asolntsev ok thanks, I guess that makes sense. But i don’t think it’s obvious that precompile is the recommended way to deploy. Maybe it would be worth reviewing the deployment documentation to be a bit more explicit with that. 

I’ve managed to get my app to precompile and run on the server. I still need to tidy things up, and have a few performance issues, but it looks like I’m nearly there. 

Thanks for your help!
