### ISSUE TITLE
Can not create custom datasource config 

### ISSUE THREAD

**Issue by ashishpmalkar** [playframework/play1#1427]
Unable to config custom datasource. I am trying load custom data source from java class on start up. but every time application start up. default database configuration gets loaded and try to connect database from application.conf file 
```

db {
  default {
    driver = com.mysql.jdbc.Driver
    host = "localhost"
....
}

```
I tried to use below still it accessing default database 
play.db.prototype.hikaricp.initializationFailFast=false
db.default.migration.initOnMigrate=false
db.default.migration.validateOnMigrate=false

### Play Version (2.5.X)
Flyaway version 3.2

### Operating System (Windows 10)

Use `uname -a` if on Linux.

**Comment by aleksandy** [comment]
@ashishpmalkar, you should ask your question [here](https://github.com/playframework/playframework/issues).

This project is play 1.x

**Comment by xael-fry** [comment]
wrong project => closing it
