### ISSUE TITLE
Play build-module fails

### ISSUE THREAD

**Issue by Axxoul** [playframework/play1#1456]
### Are you looking for help?

no

### Play Version (1.5.x / etc)

1.7.1

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 11

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

11.0.18

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. play new-module modulename
2. play build-module modulename
3. modulename is built and modulename.zip is found in dist folder

### Actual Behavior

I am using python 3.11.4

1. play new-module modulename
2. play build-module modulename

`Traceback (most recent call last):
  File "C:\play7\play", line 168, in <module>
    status = cmdloader.commands[play_command].execute(command=play_command, app=play_app, args=remaining_args, env=play_env, cmdloader=cmdloader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\play7\framework\pym\play\commands\modulesrepo.py", line 65, in execute
    build(app, args, env)
  File "C:\play7\framework\pym\play\commands\modulesrepo.py", line 323, in build
    deps = yaml.load(f.read())
           ^^^^^^^^^^^^^^^^^^^
TypeError: load() missing 1 required positional argument: 'Loader'`

It seems that the _load()_ function requires parameter _loader=Loader._
Replacing **yaml.load** with **yaml.safe_load** in modulesrepo.py seems works for me, but since I am way over my head thought I would create an issue instead of a PR.

**Comment by davidcostanzo** [comment]
I had the same problem on Ubuntu 22, Java 17.  Interestingly, this works on older versions of Ubuntu, so I think it depends on what version of yaml is installed in the system's python3.  I never figured out why Play provides its own yaml module nor why it prefers the system yaml.

I arrived at same fix **Axxoul** recommended and [https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation)

I'm also over my head in both Python and GitHub, but I'll try to submit a PR.
