### ISSUE TITLE
The imp module was removed from python 3.12

### ISSUE THREAD

**Issue by mohsen0** [playframework/play1#1457]
### Expected Behavior

To be able to run the play cli using python 3.12 

### Actual Behavior

```bash
/opt/hostedtoolcache/play-1.7.1/play deps --verbose --sync --forProd 
Traceback (most recent call last):
  File "/opt/hostedtoolcache/play-1.7.1/play", line 13, in <module>
    from play.cmdloader import CommandLoader
  File "/opt/hostedtoolcache/play-1.7.1/framework/pym/play/cmdloader.py", line 2, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
make: *** [Makefile:68: deps] Error 1
```

```
Deprecated since version 3.4, will be removed in version 3.12: The imp module is deprecated in favor of importlib.
```
https://docs.python.org/3.11/library/imp.html

### Reproducible Test Case

Try running play using python 3.12

**Comment by tazmaniax** [comment]
Is the solution to fix the Python version in the [GitHub Actions](https://github.com/playframework/play1/blob/master/.github/workflows/build-test.yml#L66) to 3.11.x?

**Comment by ath0mas** [comment]
Possibly yes to bypass the issue for the actions, but here the problem is more general and like running play on a dev computer.

**Comment by tazmaniax** [comment]
Agreed, the removal of the dependency on imp, if that is possible, is the more strategic fix that will benefit everyone.

**Comment by tazmaniax** [comment]
@ath0mas @mohsen0 possible longer-term solution here #1460

**Comment by xael-fry** [comment]
cf https://github.com/playframework/play1/pull/1465
