### ISSUE TITLE
`--sync` should be a default option for `play deps`

### ISSUE THREAD

**Issue by asolntsev** [playframework/play1#983]
I believe that the command `play deps` without `--sync` option is absolutely useless.
You always need to delete old dependencies when you are downloading new dependencies.
Otherwise you will have duplicate dependencies in the application.

In our projects, we always write `play deps --sync` which is just boring. 

I suggest that `--sync` should be ON by default.

**Comment by tazmaniax** [comment]
Agree

**Comment by asolntsev** [comment]
@xael-fry It seems that everyone is agree. What do you think?

**Comment by xael-fry** [comment]
Ok we can do it, and maybe add a ```--nosync``` option, so all users will be able to choose the behavior they want

**Comment by xael-fry** [comment]
Merged in 1.4.x with PR 1076.
Thanks

**Comment by daohodac** [comment]
I used to put my external jars in libs. Now, they are scrubbed when I run `play dependencies` Where should I put them now?

**Comment by xael-fry** [comment]
@daohodac  you can use ```--nosync``` to avoid removing the lib, on you can add your lib in dependencies.yml

**Comment by asolntsev** [comment]
Yes, I also think that adding your lib in dependencies.yml is a right
option.

Andrei Solntsev

2017-03-13 12:08 GMT+02:00 Alexandre Chatiron <notifications@github.com>:

**Comment by daohodac** [comment]
How can I add the lib in dependencies.yml?

I assume that I have a folder in my play application, say "custom-deps" with several jars. How can I add this ref in the dependencies.yml?

thank's!

**Comment by asolntsev** [comment]
@daohodac See https://github.com/codeborne/play-pdf/ for example.

You need to declate in dependencies.yml:

```
require:
    - local-jar -> flying-saucer-core-cbpatched latest.integration
    - local-jar -> flying-saucer-pdf-cbpatched latest.integration

repositories:
    - local-jars:
        type:       local
        artifact:   ${application.path}/jars/[module].jar
        contains:
            - local-jar -> *
```

**Comment by daohodac** [comment]
Thank's Andrei, it worked like a charm. and now I stick to the best practice

Dao Hodac
