### ISSUE TITLE
Use HikariCP instead of c3p0 connection pool

### ISSUE THREAD

**Issue by asolntsev** [playframework/play1#994]
HikariCP is fresh and fast, while c3p0 is old and unsupported.

https://brettwooldridge.github.io/HikariCP/

To keep compatibility, we Play 1.4.x could support both c3p0 and HikariCP, so that users can configure which one they want to use. c3p0 could be the default option for the compatibility.

**Comment by xael-fry** [comment]
Merged 
Thanks
