### ISSUE TITLE
Routes 'Assign static args' only work for first argument

### ISSUE THREAD

**Issue by chinyeelee** [playframework/play1#998]
Hi Play Framework team,

I am using play 1.2.7.2 (also tested in 1.4.2 which still contains the problem)

I want to assign a specific route to an existing Controller as described in the section:  "Assign static args"
https://www.playframework.com/documentation/1.4.x/routes

GET     /properties/condos-for-sale           App.allResidences(adType:'sale', type:'condo')

However, only the first parameter is sent to the controller, the controller only receives adType with the String value of 'sale', and the type remains as null. If I remove the first argument or swap the position of the two arguments then type will be assigned to 'condo'. But the second argument will remain as null.

Is there a work around or a fix for this? Integrating this back to 1.2 will be great so that our existing app will be less likely to break from the upgrade.

Thank you!
Chin

**Comment by xael-fry** [comment]
@chinyeelee could you show the declaration of the method allResidences in the  controller?
Thanks

**Comment by chinyeelee** [comment]
@xael-fry Thanks Alexandre, our actual api is rather complicated and beyond the scope of the question, so I simplified the usage. Tested with the following:

```
    public static void allResidences(String type, String adType){
        System.out.println(type);
        System.out.println(adType);
    }
```

Using:

`GET /properties/condos-for-sale App.allResidences(adType:'sale', type:'condo')`

Only the first item, that is adType will have the value 'sale'. type remains as null.

**Comment by xael-fry** [comment]
@chinyeelee, just removed the space after ',' should make it work.
`GET /properties/condos-for-sale App.allResidences(adType:'sale',type:'condo')`

I will add a fix to avoid this problem

**Comment by chinyeelee** [comment]
Thank you for the help! @xael-fry
